### PR TITLE
first pass at translation.json

### PR DESCRIPTION
**Pull request by morgdalaine**
html has been updated, but the javascript will need to use getTranslationByKey([key]) to populate moves, gear, etc. from translation.json

i did some spellchecking, although again, text fields in the javascript should be replaced with the appropriate name from translation.json

also, I switched mana and golem for power and ardent per v0.6

### CODE REVIEW

**Review by gromkii — APPROVED** [review]
Great work!

**Comment by morgdalaine** [comment]
Should Ideals be Hooks? I might've missed that update.

**Comment by gromkii** [comment]
Changing it to hooks wouldn't hurt. Currently working on a branch to update the section to v.06 that will have a dropdown for which type of hook it is, so I can take care of that when I merge this in.

**Comment by morgdalaine** [comment]
aww dang. line 44 of translation.json should just be `gear_name` instead of `gear_namename` 😬

**Pull request merged**
